#! /bin/sh

# XXX unprivileged?

branch=HEAD
machine=mips
machine_arch=mips64
kernel=OCTEON1

topdir=${HOME}/src/freebsd
srcdir=${topdir}/src.${branch}/src
wrkdir=${topdir}/work.${branch}/${machine_arch}

objdir=${wrkdir}/obj
dstdir=${wrkdir}/dest
nfsrootdir=${wrkdir}/nfs
tftpbootdir=${wrkdir}/tftpboot

envs="
	SRCROOT=${srcdir}
	TARGET=${machine}
	TARGET_ARCH=${machine_arch}
	KERNCONF=${kernel}
	MAKEOBJDIRPREFIX=${objdir}
	NFSROOT=${nfsrootdir}
	TFTPBOOT=${tftpbootdir}
"

makeflags="
	-DNO_CLEAN
	-DNO_KERNELCLEAN
"

make="env ${envs} make ${makeflags}"

all() {
	${make} kernel-toolchain
	${make} buildkernel
	sudo -E \
	${make} installkernel DESTDIR=${tftpbootdir}
	${make} buildworld
	sudo -E \
	${make} installworld DESTDIR=${nfsrootdir}
	sudo -E \
	${make} distribution DESTDIR=${nfsrootdir}
}

set -e

cd "${SRCROOT}"
if [ $# -eq 0 ]; then
	all
else
	for cmd in $@; do
		${make} "${cmd}"
	done
fi
cd "${OLDPWD}"
